# Starting of the aeration timer
- alias: AerationTimerTimerStart
  id: 'AerationTimerTimerStart'
  trigger:
  - platform: state
    entity_id: binary_sensor.door_livingroom_right_contact
    to: 'on'
  action:
  - service: timer.start
    entity_id: timer.aeration

# Notify when timer finished
- alias: AerationTimerFinished
  id: 'AerationTimerFinished'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
        entity_id: timer.aeration
  action:
  - service: notify.telegram_tejay
    data:
      message: "Lüften fertig"
    

# Stopping and resetting of the aeration timer      
- alias: AerationTimerStop
  id: 'AerationTimerStop'
  trigger:
  - platform: state
    entity_id: binary_sensor.door_livingroom_right_contact
    to: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.aeration
  
