homeassistant:
  packages: !include_dir_named packages

default_config:
http:
  base_url: https://home.beckedorf.me:8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_private_key

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
sensor: !include sensor.yaml
automation: !include_dir_list automations
frontend:
  themes: !include themes.yaml