homeassistant:
  packages: !include_dir_named packages

default_config:
http:
  base_url: https://home.beckedorf.me:8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_private_key

automation split: !include_dir_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
sensor: !include sensor.yaml

frontend:
  themes: !include themes.yaml
  

recorder:
  purge_keep_days: 14
  db_url: !secret recorder_db_url
  exclude: 
    domains:
    - updater
    - automation
    - device_tracker
    - group
    - scene
  # Disable auto purging, I'm doing this using automations instead
  auto_purge: false