---
# Send notification when shutdown
alias: ShutdownNotification
id: 'ShutdownNotification'
mode: single
trigger:
  platform: homeassistant
  event: shutdown
action:
  - service: notify.telegram_tejay
    data:
      message: Home Assistant is shutting down... 👋
