---
# Starting of the aeration timer
- alias: AerationTimerTimerStart
  id: 'AerationTimerTimerStart'
  trigger:
  - platform: state
    entity_id: binary_sensor.door_livingroom_right_contact
    to: 'on'
  action:
  - service: timer.start
    entity_id: timer.aeration
