---
# Notify when timer finished
alias: AerationTimerFinished
id: 'AerationTimerFinished'
mode: single
trigger:
- platform: event
  event_type: timer.finished
  event_data:
      entity_id: timer.aeration
action:
- service: notify.telegram_tejay
  data:
    message: "Es sind 15 min um und jetzt sind es im Wohnzimmer {{states('sensor.air_livingroom_humidity')}}% und im Badezimmer {{states('sensor.air_bathroom_humidity')}}%"